<?php
/**
 * Created by PhpStorm.
 * User: aymen
 * Date: 16/08/2018
 * Time: 11:00
 */
require_once 'Geometrie.php';

class Carre extends Geometrie
{
    public function __construct($cote)
    {
        $this->cote = $cote;
    }

    private $cote;

    public function whoAmI()
    {
       // parent::whoAmI(); // TODO: Change the autogenerated stub
        echo '<br>En fait je suis un carré :D';
    }

    /**
     * @return mixed
     */
    public function getCote()
    {
        return $this->cote;
    }

    /**
     * @param mixed $cote
     */
    public function setCote($cote): void
    {
        $this->cote = $cote;
    }

    public function air() {
        echo 'Je suis l air de la classe Carre <br>';
        return $this->cote*$this->cote;
    }

    public function perimetre() {
        return 4*$this->cote;
    }


}